Repository sdevalapurkar/smart-brake-monitor, pull requests merged in 2019-06, with the labels that each got.

#2 Navbar interaction cleanup
  components/LoginModal.jsx
  components/NavbarBootstrap.jsx
  components/SignupModal.jsx
  node-api-postgres/index.js
  node-api-postgres/queries.js
  pages/dashboard.js
Labels: enhancement

#1 Feature: Contact Page
  components/LoginModal.jsx
  components/SignupModal.jsx
  pages/contact.js
Labels: enhancement, good first issue

#3 JWT-based persisted auth
  .gitignore
  .gitsecret/paths/mapping.cfg
  components/LoginModal.jsx
  components/NavbarBootstrap.jsx
  components/SignupModal.jsx
  id_rsa.pub.secret
  id_rsa.secret
  node-api-postgres/index.js
  node-api-postgres/package-lock.json
  node-api-postgres/package.json
  node-api-postgres/pool.js.secret
  node-api-postgres/queries.js
  pages/contact.js
  pages/dashboard.js
  pages/index.js
Labels: enhancement

#5 Technical Debt
  node-api-postgres/index.js
  node-api-postgres/queries.js
Labels: security

#4 Landing page
  img/background.png
  img/road.jpg
  pages/contact.js
  pages/dashboard.js
  pages/index.css
  pages/index.js
Labels: enhancement

#6 Proper Logout Handling
  components/NavbarBootstrap.jsx
  components/index.css
  pages/index.js
Labels: enhancement

#7 Retrive vehicle names by user (for my account page)
  node-api-postgres/queries.js
Labels: enhancement
